### ISSUE TITLE
能否添加查看账号密码

### ISSUE THREAD

**Issue by LiangZhenX** [jaaksii/sublink#7]
能否添加查看账号密码

**Comment by jaaksii** [comment]
你的意思是在终端查看还是在网页

**Comment by LiangZhenX** [comment]
终端查看，更换密码后忘记了就进不去了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月24日(周三) 晚上7:17
收件人: ***@***.***&gt;;
抄送: "Lisa ***@***.******@***.***&gt;;
主题: Re: [jaaksii/sublink] 能否添加查看账号密码 (Issue #7)




 
你的意思是在终端查看还是在网页

**Comment by jaaksii** [comment]
已经增加初始化密码的方法，在文档的最下面
