### ISSUE TITLE
HY2转换CLASH的问题

### ISSUE THREAD

**Issue by openMJJ** [jaaksii/sublink#8]
hy2://xxxxx@XXXX?obfs=salamander&obfs-password=XXX&insecure=1#LIGAAAA-1T%20hysteria2
这个格式转换为CLASH后，缺少了obfs,obfs-password两个参数。
导致节点不同，大佬能修复一下吗？

**Comment by jaaksii** [comment]
私我发节点，没法猜

**Comment by jaaksii** [comment]
已经添加obfs参数，由于没有节点测试不确定是否能用，请自行尝试
